import type { ConsentService, User } from "./consent-types";

export const DEMO_USERS: User[] = [
  {
    id: "user-nurken",
    email: "nurken.kad@gmail.com",
    password: "12345678",
    name: "Нуркен",
  },
  {
    id: "user-bayet",
    email: "bayet.zh@gmail.com",
    password: "12345678",
    name: "Баят",
  },
];

const daysAgo = (d: number) =>
  new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();

// helper для краткости
function svc(s: Omit<ConsentService, "status" | "grantedAt"> & { daysAgo: number }): ConsentService {
  const { daysAgo: d, ...rest } = s;
  return { ...rest, status: "active", grantedAt: daysAgo(d) };
}

// ---------- Каталог сервисов ----------
// Нуркен — финансы + госуслуги + работа + немного развлечений
export const SERVICES_NURKEN: ConsentService[] = [
  svc({
    id: "kaspi",
    name: "Kaspi.kz",
    icon: "🏦",
    category: "Банк",
    accent: "0.66 0.18 30",
    description: "Банковские услуги, переводы, маркетплейс",
    risk: "high",
    riskExplanation: "Полный доступ к финансовой жизни: карты, платежи, история покупок.",
    daysAgo: 420,
    dataPoints: [
      { id: "passport", label: "Паспортные данные", granted: true, required: true },
      { id: "iin", label: "ИИН", granted: true, required: true },
      { id: "phone", label: "Телефон", granted: true },
      { id: "accounts", label: "Банковские счета", granted: true },
      { id: "transactions", label: "История транзакций", granted: true },
      { id: "geo", label: "Геолокация", granted: true },
    ],
  }),
  svc({
    id: "egov",
    name: "eGov.kz",
    icon: "🏛️",
    category: "Госуслуги",
    accent: "0.55 0.16 240",
    description: "Государственные услуги Казахстана",
    risk: "medium",
    riskExplanation: "Идентифицирующие данные. Используются для оформления документов.",
    daysAgo: 800,
    dataPoints: [
      { id: "iin", label: "ИИН", granted: true, required: true },
      { id: "fio", label: "ФИО", granted: true, required: true },
      { id: "address", label: "Адрес регистрации", granted: true },
      { id: "family", label: "Семейное положение", granted: true },
      { id: "property", label: "Имущество", granted: true },
    ],
  }),
  svc({
    id: "halyk",
    name: "Halyk Bank",
    icon: "💳",
    category: "Банк",
    accent: "0.55 0.18 150",
    description: "Зарплатный проект и кредитная линия",
    risk: "high",
    riskExplanation: "Зарплатные начисления и кредитная история.",
    daysAgo: 600,
    dataPoints: [
      { id: "passport", label: "Паспортные данные", granted: true, required: true },
      { id: "salary", label: "Зарплатные начисления", granted: true },
      { id: "credit", label: "Кредитная история", granted: true },
      { id: "phone", label: "Телефон", granted: true },
    ],
  }),
  svc({
    id: "linkedin",
    name: "LinkedIn",
    icon: "💼",
    category: "Карьера",
    accent: "0.45 0.18 240",
    description: "Профессиональная сеть и поиск работы",
    risk: "low",
    riskExplanation: "Публичный профиль и контакты.",
    daysAgo: 230,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "name", label: "ФИО", granted: true },
      { id: "experience", label: "Опыт работы", granted: true },
      { id: "contacts", label: "Список контактов", granted: true },
    ],
  }),
  svc({
    id: "wolt",
    name: "Wolt",
    icon: "🛵",
    category: "Доставка",
    accent: "0.7 0.16 200",
    description: "Доставка еды и продуктов",
    risk: "low",
    riskExplanation: "Адрес доставки и контакты.",
    daysAgo: 90,
    dataPoints: [
      { id: "phone", label: "Телефон", granted: true, required: true },
      { id: "geo", label: "Геолокация", granted: true },
      { id: "address", label: "Домашний адрес", granted: true },
      { id: "card", label: "Платёжная карта", granted: true },
    ],
  }),
  svc({
    id: "instagram",
    name: "Instagram",
    icon: "📸",
    category: "Соцсеть",
    accent: "0.6 0.22 350",
    description: "Социальная сеть Meta",
    risk: "medium",
    riskExplanation: "Поведенческий профиль, контакты, геолокация фото.",
    daysAgo: 1200,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "phone", label: "Телефон", granted: true },
      { id: "contacts", label: "Список контактов", granted: true },
      { id: "geo", label: "Геолокация", granted: true },
      { id: "photos", label: "Фото и видео", granted: true },
    ],
  }),
  svc({
    id: "uber",
    name: "Uber",
    icon: "🚕",
    category: "Транспорт",
    accent: "0.25 0.02 270",
    description: "Заказ такси",
    risk: "medium",
    riskExplanation: "История поездок раскрывает ваш образ жизни.",
    daysAgo: 340,
    dataPoints: [
      { id: "phone", label: "Телефон", granted: true, required: true },
      { id: "geo", label: "Геолокация", granted: true, required: true },
      { id: "trips", label: "История поездок", granted: true },
      { id: "card", label: "Платёжная карта", granted: true },
    ],
  }),
  svc({
    id: "chatgpt",
    name: "ChatGPT",
    icon: "🤖",
    category: "AI-сервис",
    accent: "0.55 0.15 170",
    description: "Чат-бот OpenAI",
    risk: "medium",
    riskExplanation: "История разговоров может содержать конфиденциальные данные.",
    daysAgo: 180,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "phone", label: "Телефон", granted: true },
      { id: "history", label: "История чатов", granted: true },
    ],
  }),
];

// Баят — студент: учёба + развлечения + меньше финансов
export const SERVICES_BAYET: ConsentService[] = [
  svc({
    id: "egov",
    name: "eGov.kz",
    icon: "🏛️",
    category: "Госуслуги",
    accent: "0.55 0.16 240",
    description: "Государственные услуги Казахстана",
    risk: "medium",
    riskExplanation: "Идентифицирующие данные.",
    daysAgo: 500,
    dataPoints: [
      { id: "iin", label: "ИИН", granted: true, required: true },
      { id: "fio", label: "ФИО", granted: true, required: true },
      { id: "address", label: "Адрес регистрации", granted: true },
    ],
  }),
  svc({
    id: "kaspi",
    name: "Kaspi.kz",
    icon: "🏦",
    category: "Банк",
    accent: "0.66 0.18 30",
    description: "Студенческая карта и переводы",
    risk: "high",
    riskExplanation: "Карта, платежи и история покупок.",
    daysAgo: 200,
    dataPoints: [
      { id: "passport", label: "Паспортные данные", granted: true, required: true },
      { id: "iin", label: "ИИН", granted: true, required: true },
      { id: "phone", label: "Телефон", granted: true },
      { id: "transactions", label: "История транзакций", granted: true },
    ],
  }),
  svc({
    id: "platonus",
    name: "Platonus",
    icon: "🎓",
    category: "Учёба",
    accent: "0.5 0.16 280",
    description: "Учебная платформа университета",
    risk: "low",
    riskExplanation: "Академические данные: оценки, расписание.",
    daysAgo: 720,
    dataPoints: [
      { id: "iin", label: "ИИН", granted: true, required: true },
      { id: "grades", label: "Академические оценки", granted: true },
      { id: "schedule", label: "Расписание", granted: true },
      { id: "attendance", label: "Посещаемость", granted: true },
    ],
  }),
  svc({
    id: "coursera",
    name: "Coursera",
    icon: "📚",
    category: "Учёба",
    accent: "0.5 0.18 240",
    description: "Онлайн-курсы",
    risk: "low",
    riskExplanation: "История обучения и сертификаты.",
    daysAgo: 300,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "name", label: "ФИО", granted: true },
      { id: "progress", label: "Прогресс обучения", granted: true },
    ],
  }),
  svc({
    id: "steam",
    name: "Steam",
    icon: "🎮",
    category: "Игры",
    accent: "0.4 0.12 240",
    description: "Игровая платформа Valve",
    risk: "medium",
    riskExplanation: "Платёжная информация и игровая активность.",
    daysAgo: 1500,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "card", label: "Платёжная карта", granted: true },
      { id: "library", label: "Библиотека игр", granted: true },
      { id: "playtime", label: "История игр", granted: true },
      { id: "friends", label: "Список друзей", granted: true },
    ],
  }),
  svc({
    id: "discord",
    name: "Discord",
    icon: "💬",
    category: "Мессенджер",
    accent: "0.55 0.18 270",
    description: "Голосовые и текстовые чаты",
    risk: "medium",
    riskExplanation: "Сообщения, голосовые звонки, серверы.",
    daysAgo: 900,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "phone", label: "Телефон", granted: true },
      { id: "messages", label: "История сообщений", granted: true },
      { id: "voice", label: "Голосовая активность", granted: true },
    ],
  }),
  svc({
    id: "netflix",
    name: "Netflix",
    icon: "🎬",
    category: "Стриминг",
    accent: "0.55 0.22 27",
    description: "Сервис видеостриминга",
    risk: "low",
    riskExplanation: "История просмотров и рекомендации.",
    daysAgo: 410,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "card", label: "Платёжная карта", granted: true },
      { id: "history", label: "История просмотров", granted: true },
    ],
  }),
  svc({
    id: "spotify",
    name: "Spotify",
    icon: "🎵",
    category: "Музыка",
    accent: "0.7 0.18 145",
    description: "Музыкальный стриминг",
    risk: "low",
    riskExplanation: "Музыкальные предпочтения и плейлисты.",
    daysAgo: 540,
    dataPoints: [
      { id: "email", label: "Email", granted: true, required: true },
      { id: "playlists", label: "Плейлисты", granted: true },
      { id: "history", label: "История прослушиваний", granted: true },
    ],
  }),
  svc({
    id: "tiktok",
    name: "TikTok",
    icon: "🎶",
    category: "Соцсеть",
    accent: "0.55 0.2 350",
    description: "Короткие видео",
    risk: "high",
    riskExplanation: "Глубокий поведенческий профиль и доступ к контактам.",
    daysAgo: 250,
    dataPoints: [
      { id: "phone", label: "Телефон", granted: true, required: true },
      { id: "contacts", label: "Список контактов", granted: true },
      { id: "geo", label: "Геолокация", granted: true },
      { id: "behavior", label: "Поведенческий профиль", granted: true },
    ],
  }),
  svc({
    id: "telegram",
    name: "Telegram",
    icon: "✈️",
    category: "Мессенджер",
    accent: "0.65 0.14 230",
    description: "Мессенджер с облачным хранением",
    risk: "low",
    riskExplanation: "Контакты и метаданные сообщений.",
    daysAgo: 1100,
    dataPoints: [
      { id: "phone", label: "Телефон", granted: true, required: true },
      { id: "contacts", label: "Список контактов", granted: true },
    ],
  }),
];

export function getServicesForUser(userId: string): ConsentService[] {
  if (userId === "user-nurken") return SERVICES_NURKEN;
  if (userId === "user-bayet") return SERVICES_BAYET;
  return [];
}
